PATH:
  project_dir: /  # 项目根目录
  data_online_dir: https://github.com/VeritasYin/STGCN_IJCAI-18/tree/master/data_loader/PeMS-M.zip
  data_root_dir:  /Users/zfwang/machinelearning/datasets/  # 本地数据根目录
  data_local_dir: traffic
  data_fold: PeMS-M
  data_file:
    - PeMS-M.zip
    - W_228.csv
    - V_228.csv
  model_dir: models  # 模型
DATA:
  train_size: 0.5
  validation_size: 0.2
  test_size: 0.3

  batch_size: 64
  input_sequence_length: 12
  forecast_horizon: 3
  multi_horizon: False
  buffer_size: 
MODEL:
  epochs: 12
  learning_rate: 1e-3